--潜行者-狂徒-项链技能_优先1
--if GetSpellInfo("艾泽拉斯之心精华") == "聚能艾泽里特射线" then
--	return CastOnTarget(#艾泽拉斯之心精华#) or 0
--end
--if GetSpellInfo("艾泽拉斯之心精华") == "仇敌之血" then
--	return CastOnTarget(#艾泽拉斯之心精华#, run("仇敌之血可用"))
--end
--return CastOnTarget(#艾泽拉斯之心精华#)
